### ISSUE TITLE
Symantec Cert Waring - False Positives

### ISSUE THREAD

**Issue by jskilton** [mozilla/tls-observatory#397] opened 2019-11-15 21:59 UTC
![Screen Shot 2019-11-15 at 4 59 04 PM](https://user-images.githubusercontent.com/8955831/68978633-4ffca600-07c9-11ea-9e6b-d393fc788a4d.png)

My Scan
https://observatory.mozilla.org/analyze/www.borderfree.com

Forum on CF discussing the issue. 
https://community.cloudflare.com/t/this-site-uses-a-symantec-cert-issued-on-or-after-june-1-2016-and-will-be-distrusted-by-firefox-63-and-chrome-70-please-replace-its-certificate-immediately/99663

**Comment by anders-kiaer** [comment] 2019-11-24 07:25
We get the same warning on most Azure Web Apps.

Related/duplicate of #395? If so, maybe it will be fixed with #396.

**Comment by g-k** [comment] 2021-01-25 15:10
Yep, same as https://github.com/mozilla/tls-observatory/issues/395#issuecomment-766882512

https://observatory.mozilla.org/analyze/www.borderfree.com#tls is not showing the warning.

**Closed by g-k** 2021-01-25 15:10 UTC
